<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="Spectre.Console.Cli" Version="0.53.0" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\src\Escape.Core\Escape.Core.csproj" />
	  <ProjectReference Include="..\..\src\Escape.Extensions.UI\Escape.Extensions.UI.csproj" />
	  <ProjectReference Include="..\..\src\Escape.Resources\Escape.Resources.csproj" />
	</ItemGroup>

	<!-- asset (sym)linking !-->
	<Import Project="..\..\src\Escape.Resources\LinkAssets.targets" />

	<ItemGroup>
		<AssetLinkProject Include="Escape.Editors.ResourceEditor.csproj" />
	</ItemGroup>

	<!-- scripts !-->
	<Import Project="..\..\src\Escape.Core\Script.targets"/>

</Project>
